Repository eclipse-aaspe/server, pull requests merged in 2024-06, with the labels that each got.

#274 Fix GitHub Workflows and Release Creation, and Adapt Documentation
  .github/changelog_configuration.json
  .github/workflows/code-analysis.yml
  .github/workflows/prerelease-on-merge-to-main.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  src/AasCore.Aas3_0/AasCore.Aas3_0.csproj
  src/AasSecurity/AasSecurity.csproj
  src/AasxCsharpLibrary/AasxCsharpLibrary.csproj
  src/AasxServer.sln
  src/AasxServerAspNetCore/AasxServerAspNetCore.csproj
  src/AasxServerBlazor/AasxServerBlazor.csproj
  src/AasxServerStandardBib/AasxServerStandardBib.csproj
  src/DataTransferObjects/DataTransferObjects.csproj
  src/ExampleClient/ExampleClient.csproj
  src/IO.Swagger.Lib.V3/IO.Swagger.Lib.V3.csproj
  src/IO.Swagger.Registry.Lib.V3/IO.Swagger.Registry.Lib.V3.csproj
  src/es6numberserializer/es6numberserializer.csproj
  src/jsoncanonicalizer/jsoncanonicalizer.csproj
Labels: enhancement

#216 fixes thumbnail contenttype null exception
  src/AasxCsharpLibrary/AdminShellPackageEnv.cs
  src/AasxServerStandardBib/Services/AdminShellPackageEnvironmentService.cs
Labels: bug

#275 Clean up CodeQL issues
  src/.editorconfig
  src/AasCore.Aas3_0/types.cs
  src/AasxCsharpLibrary/AasxCompatibilityModels/V20/AdminShellUtil.cs
  src/AasxCsharpLibrary/Extensions/ExtendObject.cs
  src/AasxServerStandardBib/Program.cs
  src/AasxServerStandardBib/SampleNodeManager.cs
Labels: bug

#276 Fix Thread-unsafe use of a static ICryptoTransform field
  src/AasxCsharpLibrary/AasxCompatibilityModels/V20/AdminShell.cs
Labels: security-issue

#279 Update nightly workflow for more accurate release notes
  .github/workflows/prerelease-on-merge-to-main.yml
Labels: ignore

#280 Fix Release and develop workflow as well
  .github/workflows/draft-prerelease-on-pushed-tag.yml
  .github/workflows/draft-release-on-merge-to-release-branch.yml
Labels: ignore

#281 Fix Workflow issues with release number and changelog
  .github/changelog_configuration.json
  .github/workflows/build-and-publish-docker-images.yml
  .github/workflows/draft-prerelease-on-pushed-tag.yml
  .github/workflows/draft-release-on-merge-to-release-branch.yml
  .github/workflows/prerelease-on-merge-to-main.yml
  src/BuildVersionNumber.ps1
Labels: ignore

#282 Fix inconvenient bugs in workflows
  .github/changelog_configuration.json
  .github/workflows/create-developer-prerelease.yml
  .github/workflows/draft-release-on-merge-to-release-branch.yml
  .github/workflows/prerelease-on-merge-to-main.yml
  src/AasxServer.sln
Labels: ignore

#278 Fix for User-controlled bypass of sensitive method in AasSecurityAuthorizationHandler
  .github/workflows/code-analysis.yml
  src/.editorconfig
  src/AasSecurity/AasSecurityAuthorizationHandler.cs
  src/AasSecurity/GlobalSecurityVariables.cs
  src/AasSecurity/ISecurityService.cs
  src/AasSecurity/SecurityService.cs
  src/AasxCsharpLibrary/AasxCompatibilityModels/V20/AdminShell.cs
  src/AasxServerStandardBib/Services/LogSanitizer.cs
Labels: security-issue

#249 Freezor/minor styling refactoring of blazor files
  CHANGELOG.md
  src/AasxServerBlazor/Data/AASService.cs
  src/AasxServerBlazor/Data/BlazorSessionService.cs
  src/AasxServerBlazor/Data/CredentialService.cs
  src/AasxServerBlazor/Data/TreeStyle.cs
  src/AasxServerBlazor/Pages/About.razor
  src/AasxServerBlazor/Pages/Assetid.razor
  src/AasxServerBlazor/Pages/Atex.razor
  src/AasxServerBlazor/Pages/Counter.razor
  src/AasxServerBlazor/Pages/Db.razor
  src/AasxServerBlazor/Pages/Index.razor
  src/AasxServerBlazor/Pages/Pcf2.razor
  src/AasxServerBlazor/Pages/Submodels.razor
  src/AasxServerBlazor/Pages/Tree.razor
  src/AasxServerBlazor/Pages/TreePage.razor
  src/AasxServerBlazor/Shared/MainLayout.razor
  src/AasxServerBlazor/Shared/NavMenu.razor
  src/AasxServerBlazor/wwwroot/SpecPI40_t.png
  src/AasxServerBlazor/wwwroot/css/site.css
  src/AasxServerBlazor/wwwroot/css/treeStyles.css
  src/AasxServerStandardBib/Program.cs
Labels: cleanup

#283 fix styling of MainLayout.razor
  src/AasxServerBlazor/Shared/MainLayout.razor
Labels: cleanup

#285 Remove I40Language references
  CHANGELOG.md
  src/AasxServerStandardBib/I40Message.cs
  src/AasxServerStandardBib/Program.cs
  src/AasxServerStandardBib/i40Language.cs
Labels: cleanup

#286 Fix missing usage of externalRepository and "AASREPOSITORY" environment property
  src/AasxServerStandardBib/Program.cs
  src/IO.Swagger.Registry.Lib.V3/Services/AasRegistryService.cs
  src/IO.Swagger.Registry.Lib.V3/Services/RegistryInitializerService.cs
Labels: bug

#288 Fix dockerfiles missing dotnet restore
  .github/workflows/check-release.yml
  .github/workflows/prerelease-on-merge-to-main.yml
  CHANGELOG.md
  src/.editorconfig
  src/AasCore.Aas3_0/AasCore.Aas3_0.csproj
  src/AasSecurity/AasSecurity.csproj
  src/AasxCsharpLibrary/AasxCompatibilityModels/V20/AdminShell.cs
  src/AasxCsharpLibrary/AasxCsharpLibrary.csproj
  src/AasxServerAspNetCore/AasxServerAspNetCore.csproj
  src/AasxServerBlazor/AasxServerBlazor.csproj
  src/AasxServerDB/AasxServerDB.csproj
  src/AasxServerStandardBib/AasxServerStandardBib.csproj
  src/DataTransferObjects/DataTransferObjects.csproj
  src/ExampleClient/ExampleClient.csproj
  src/IO.Swagger.Lib.V3/IO.Swagger.Lib.V3.csproj
  src/IO.Swagger.Registry.Lib.V3/IO.Swagger.Registry.Lib.V3.csproj
  src/current_version.cfg
  src/docker/Dockerfile-AasxServerAspNetCore
  src/docker/Dockerfile-AasxServerAspNetCore-arm32
  src/docker/Dockerfile-AasxServerAspNetCore-arm64
  src/docker/Dockerfile-AasxServerBlazor
  src/docker/Dockerfile-AasxServerBlazor-arm32
  src/docker/Dockerfile-AasxServerBlazor-arm64
  src/es6numberserializer/es6numberserializer.csproj
  src/jsoncanonicalizer/jsoncanonicalizer.csproj
Labels: bug

#289 Fix release docker workflow
  .github/workflows/build-and-publish-docker-images.yml
Labels: bug

#290 Create unit test project and add it into process to run in every build
  .github/workflows/check-release.yml
  .github/workflows/prerelease-on-merge-to-main.yml
  .github/workflows/test-report.yml
  src/.editorconfig
  src/AasSecurity/AssemblyInfo.cs
  src/AasSecurityTests/AasSecurityContextTest.cs
  src/AasSecurityTests/AasSecurityTests.csproj
  src/AasSecurityTests/GlobalUsings.cs
  src/AasxServer.sln
Labels: test

#291 add labels to docker images
  .github/workflows/check-release.yml
  .github/workflows/prerelease-on-merge-to-main.yml
  .github/workflows/test-report.yml
  src/AasxServer.sln
Labels: ignore

#292 Upgrade most packages to net8.0 compatibility
  src/AasSecurityTests/AasSecurityTests.csproj
  src/AasxCsharpLibrary/AasxCsharpLibrary.csproj
  src/AasxServerAspNetCore/AasxServerAspNetCore.csproj
  src/AasxServerBlazor/AasxServerBlazor.csproj
  src/AasxServerDB/AasxServerDB.csproj
  src/AasxServerStandardBib/AasxServerStandardBib.csproj
  src/AasxServerStandardBib/Credentials.cs
  src/IO.Swagger.Lib.V3/IO.Swagger.Lib.V3.csproj
  src/IO.Swagger.Registry.Lib.V3/IO.Swagger.Registry.Lib.V3.csproj
Labels: cleanup

#294 Fix Swagger MessageType issue and further nullable fixes
  src/IO.Swagger.Lib.V3/Controllers/AASXFileServerAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/AssetAdministrationShellRepositoryAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/ConceptDescriptionRepositoryAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/DescriptionAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/SerializationAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/SubmodelRepositoryAPIApi.cs
  src/IO.Swagger.Lib.V3/Middleware/ExceptionMiddleware.cs
  src/IO.Swagger.Lib.V3/Models/Message.cs
  src/IO.Swagger.Lib.V3/Startup.cs
  src/IO.Swagger.Registry.Lib.V3/Models/Message.cs
  src/IO.Swagger.Registry.Lib.V3/Startup.cs
Labels: bug

#296 Fix nullable handling and issue #295
  .github/changelog_configuration.json
  src/IO.Swagger.Lib.V3/Controllers/AASXFileServerAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/AssetAdministrationShellRepositoryAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/ConceptDescriptionRepositoryAPIApi.cs
  src/IO.Swagger.Lib.V3/Controllers/SubmodelRepositoryAPIApi.cs
  src/IO.Swagger.Lib.V3/Filters/BasePathFilter.cs
  src/IO.Swagger.Lib.V3/Filters/GeneratePathParamsValidationFilter.cs
  src/IO.Swagger.Lib.V3/Formatters/AasRequestFormatter.cs
  src/IO.Swagger.Lib.V3/Formatters/AasResponseFormatter.cs
  src/IO.Swagger.Lib.V3/Models/BaseOperationResult.cs
  src/IO.Swagger.Lib.V3/Models/Description.cs
  src/IO.Swagger.Lib.V3/Models/GetPathItemsResult.cs
  src/IO.Swagger.Lib.V3/Models/GetReferencesResult.cs
  src/IO.Swagger.Lib.V3/Models/GetSubmodelElementsResult.cs
  src/IO.Swagger.Lib.V3/Models/OperationRequest.cs
  src/IO.Swagger.Lib.V3/Models/OperationResult.cs
  src/IO.Swagger.Lib.V3/Models/Result.cs
  src/IO.Swagger.Lib.V3/Models/ServiceDescription.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/Mappers/MetadataMappers/RequestMetadataMapper.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/Mappers/MetadataMappers/ResponseMetadataMapper.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/Mappers/MetadataMappers/ResponseMetadataTransformer.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/Mappers/ValueMappers/RequestValueMapper.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/Mappers/ValueMappers/ValueOnlyJsonDeserializer.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/Mappers/ValueMappers/ValueOnlyJsonSerializer.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/PathModifier/PathTransformer.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/SerializationModifiersValidator.cs
  src/IO.Swagger.Lib.V3/Services/JsonQueryDeserializer.cs
  src/IO.Swagger.Lib.V3/Services/PaginationService.cs
  src/IO.Swagger.Lib.V3/Services/ReferenceModifierService.cs
Labels: bug

#298 Fix problem with release workflow and update automatic changelog config
  .github/changelog_configuration.json
  .github/workflows/create-developer-prerelease.yml
Labels: ignore

#301 Add tests for IO.Swagger.Registry.Lib.V3
  src/AasxServer.sln
  src/IO.Swagger.Lib.V3/IO.Swagger.Lib.V3.csproj
  src/IO.Swagger.Registry.Lib.V3.Tests/GlobalUsings.cs
  src/IO.Swagger.Registry.Lib.V3.Tests/IO.Swagger.Registry.Lib.V3.Tests.csproj
  src/IO.Swagger.Registry.Lib.V3.Tests/Services/AasDescriptorPaginationServiceTests.cs
  src/IO.Swagger.Registry.Lib.V3/IO.Swagger.Registry.Lib.V3.csproj
Labels: test

#302 update existing references to dotnet 8
  .github/workflows/check-release.yml
  .github/workflows/code-analysis.yml
  .github/workflows/create-developer-prerelease.yml
  .github/workflows/draft-release-on-merge-to-release-branch.yml
  README.md
  src/global.json
Labels: cleanup

#287 Add Timestamp to Database
  src/AasCore.Aas3_0/xmlization.cs
  src/AasxServerBlazor/Pages/Atex.razor
  src/AasxServerBlazor/Pages/Atex2.razor
  src/AasxServerBlazor/Pages/Db.razor
  src/AasxServerBlazor/Pages/TreePage.razor
  src/AasxServerBlazor/wwwroot/db-schema.jpg
  src/AasxServerDB/AasxServerDB.csproj
  src/AasxServerDB/Converter.cs
  src/AasxServerDB/Entities/AASSet.cs
  src/AasxServerDB/Entities/SMESet.cs
  src/AasxServerDB/Entities/SMSet.cs
  src/AasxServerDB/EntityFW.cs
  src/AasxServerDB/Migrations/Postgres/20240604060839_InitialCreate.Designer.cs
  src/AasxServerDB/Migrations/Postgres/20240604060839_InitialCreate.cs
  src/AasxServerDB/Migrations/Postgres/PostgreAasContextModelSnapshot.cs
  src/AasxServerDB/Migrations/Sqlite/20240604060814_InitialCreate.Designer.cs
  src/AasxServerDB/Migrations/Sqlite/20240604060814_InitialCreate.cs
  src/AasxServerDB/Migrations/Sqlite/SqliteAasContextModelSnapshot.cs
  src/AasxServerDB/PageRetriever.cs
  src/AasxServerDB/Query.cs
  src/AasxServerDB/Result/SMEResult.cs
  src/AasxServerDB/Result/SMResult.cs
  src/AasxServerDB/TimeStamp.cs
  src/AasxServerDB/VisitorAASX.cs
  src/AasxServerStandardBib/Program.cs
  src/AasxServerStandardBib/SecurityClient.cs
  src/AasxServerStandardBib/Services/AasxFileServerInterfaceService.cs
  src/AasxServerStandardBib/Services/AdminShellPackageEnvironmentService.cs
  src/AasxServerStandardBib/TimeSeries.cs
  src/IO.Swagger.Lib.V3/Controllers/SubmodelRepositoryAPIApi.cs
  src/IO.Swagger.Registry.Lib.V3/Services/AasRegistryService.cs
Labels: enhancement

#303 Create new testing project for AasxServerBlazor
  src/AasCore.Aas3_0/AasCore.Aas3_0.csproj
  src/AasSecurity/AasSecurity.csproj
  src/AasSecurityTests/AasSecurityTests.csproj
  src/AasxCsharpLibrary/AasxCsharpLibrary.csproj
  src/AasxServer.sln
  src/AasxServerAspNetCore/AasxServerAspNetCore.csproj
  src/AasxServerBlazor/AasxServerBlazor.csproj
  src/AasxServerBlazor/BlazorServerStarter.cs
  src/AasxServerBlazorTests/AasxServerBlazorTests.csproj
  src/AasxServerBlazorTests/Configuration/DependencyRegistryTests.cs
  src/AasxServerBlazorTests/GlobalUsings.cs
  src/AasxServerDB/AasxServerDB.csproj
  src/AasxServerStandardBib/AasxServerStandardBib.csproj
  src/DataTransferObjects/DataTransferObjects.csproj
  src/es6numberserializer/es6numberserializer.csproj
Labels: test

#306 Add release notes of previous releases to CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#309 Remove PcfEnergyModel1.0 as it is not used at the moment
  src/AasxServerStandardBib/EnergyModel.cs
  src/AasxServerStandardBib/EnergyModel_SourceSystem_Azure.cs
  src/AasxServerStandardBib/PrefEnergyModel10.cs
  src/AasxServerStandardBib/Program.cs
Labels: refactoring

#310 Refine Docker Build Process for Multiplatform Support (incl. M3, AMD, ARM/32)
  .github/workflows/build-and-publish-docker-images.yml
  .github/workflows/check-release.yml
  .github/workflows/prerelease-on-merge-to-main.yml
  README.md
  src/AasxServer.sln
  src/docker/Dockerfile-AasxServerAspNetCore
  src/docker/Dockerfile-AasxServerAspNetCore-arm32
  src/docker/Dockerfile-AasxServerAspNetCore-arm64
  src/docker/Dockerfile-AasxServerBlazor
  src/docker/Dockerfile-AasxServerBlazor-arm32
  src/docker/Dockerfile-AasxServerBlazor-arm64
Labels: feature

#311 Fix missing port exposing in docker container which preventer Blazor Ui from being shown
  src/docker/Dockerfile-AasxServerBlazor
  src/docker/docker-compose-demo.yaml
Labels: bug

#313 fix docker build steps and ports for dotnet 8.0
  src/docker/Dockerfile-AasxServerBlazor
  src/docker/docker-compose-demo.yaml
  src/docker/docker-compose.yaml
Labels: bug

#317 Fix docker ports on the build and default port
  src/AasxServerBlazor/BlazorServerStarter.cs
  src/AasxServerBlazor/Configuration/ServerConfiguration.cs
  src/docker/Dockerfile-AasxServerAspNetCore
  src/docker/Dockerfile-AasxServerBlazor
  src/docker/docker-compose-demo.yaml
  src/docker/docker-compose.yaml
Labels: bug

#318 Fixed Endpoint Query Parameter Handling
  src/AasxServerBlazor/Properties/launchSettings.json
  src/AasxServerBlazorTests/AasxServerBlazorTests.csproj
  src/AasxServerStandardBib/AasxServerStandardBib.csproj
  src/IO.Swagger.Lib.V3.Tests/Controllers/SubmodelRepositoryAPIApiControllerTests.cs
  src/IO.Swagger.Lib.V3.Tests/Models/PagedResultTests.cs
  src/IO.Swagger.Lib.V3.Tests/Models/PaginationParameterTests.cs
  src/IO.Swagger.Lib.V3.Tests/SerializationModifiers/LevelExtent/LevelExtentTransformerTests.cs
  src/IO.Swagger.Lib.V3.Tests/SerializationModifiers/PathModifier/PathTransformerTests.cs
  src/IO.Swagger.Lib.V3.Tests/Services/Base64UrlDecoderServiceTests.cs
  src/IO.Swagger.Lib.V3.Tests/Services/LevelExtentModifierServiceTest.cs
  src/IO.Swagger.Lib.V3.Tests/Services/PaginationServiceTests.cs
  src/IO.Swagger.Lib.V3.Tests/Services/PathModifierServiceTests.cs
  src/IO.Swagger.Lib.V3/AssemblyInfo.cs
  src/IO.Swagger.Lib.V3/Controllers/SubmodelRepositoryAPIApi.cs
  src/IO.Swagger.Lib.V3/Interfaces/IBase64UrlDecoderService.cs
  src/IO.Swagger.Lib.V3/Interfaces/ILevelExtentModifierService.cs
  src/IO.Swagger.Lib.V3/Interfaces/IPaginationService.cs
  src/IO.Swagger.Lib.V3/Interfaces/IPathModifierService.cs
  src/IO.Swagger.Lib.V3/Models/PagedResult.cs
  src/IO.Swagger.Lib.V3/Models/PaginationParameters.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/LevelExtent/LevelExtentTransformer.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/PathModifier/PathModifierContext.cs
  src/IO.Swagger.Lib.V3/SerializationModifiers/PathModifier/PathTransformer.cs
  src/IO.Swagger.Lib.V3/Services/Base64UrlDecoderService.cs
  src/IO.Swagger.Lib.V3/Services/LevelExtentModifierService.cs
  src/IO.Swagger.Lib.V3/Services/PaginationService.cs
  src/IO.Swagger.Lib.V3/Services/PathModifierService.cs
Labels: bug, cleanup
